### ISSUE TITLE
[Feature request] Reading vertices from external files such as CSV files

### ISSUE THREAD

**Issue by OpenFoam-User** [FloSewn/TQMesh#11]
It would be much convenient to read the list of vertices from extenal files such CSV files. In my opinion, that would be much better than manually adding the vertices.

The CSV file should contains the `x`, and `y` columns or possibly the four columns: `x`, `y`, `Scale parameter`, and `Range parameter`.

Please feel free to close this if you think that defeats the purpose of using `.para` files in the first place.
Thank you

**Comment by FloSewn** [comment]
Awesome idea! I will try to implement this in the near future.

Greetings 
Flo

**Comment by FloSewn** [comment]
Hey there,

I added the feature to read lists of vertices as boundary definitions in the newest release.
You can check out the files "input/06_airfoil_from_csv.para" and "src/examples/06_airfoild_from_csv.cpp" to see how it works.

Greetings
Flo
