### ISSUE TITLE
run_tests: Segmentation fault 

### ISSUE THREAD

**Issue by eriks-aidotse** [FloSewn/TQMesh#2]
Hi! Thanks for providing TQMesh, seems to be really nice. However I fail to get it up and running. After building the run_test is failing:
`# 
#===== Geometry tests =====
# 
#===== QTree tests =====
# 
#===== Container tests =====
Segmentation fault (core dumped)`

I have tied, the latest branch, v1.0 and v.1.0.1; on Ubuntu 22.04.

/Erik

**Comment by FloSewn** [comment]
Hey Erik,

thanks for the information!

Curiously, this error does not appear in my case.... 
Can you tell me which compiler (an version) you are using? 
Would it be possible that you run_test() with valgrind? Then we can see where the segmentation fault occurs.

Maybe you could also try to compile without the "-DNDEBUG" flag (you can set this in CMakeLists.txt in the root directory in lines 12-15).

Sorry that it works a bit bumpy - unfortunately TQMesh is just a small spare time project of mine - but I'm happy about everyone who uses it.

Best regards

Flo

**Comment by FloSewn** [comment]
Hey there,

I could replicate the error using g++-10. 
So you do not need to send me the info.

Hopefully I will fix it the next days.

Best regards
Flo

**Comment by FloSewn** [comment]
Hello Erik,

I might have fixed the bug. 
The updated code is under the new release v1.0.2

It would be great, if you could tell me if it worked.

Best regards
Flo

**Comment by eriks-aidotse** [comment]
Hi Flo!

V1.0.2 is working well. No  warnings during build and test went trough. I am using Ubuntu 22.04, that comes with cmake version 3.22.1 and gcc (Ubuntu 11.2.0-19ubuntu1) 11.2.0.

I will later try some non trivial meshing. Thanks for providing TQMesh! And thanks for the support!

/Erik

**Comment by eriks-aidotse** [comment]
Hi Flo!

V1.0.2 is working well. No  warnings during build and the test went trough. I am using Ubuntu 22.04, that comes with cmake version 3.22.1 and gcc (Ubuntu 11.2.0-19ubuntu1) 11.2.0.

I will later try some non trivial meshing. Thanks for providing TQMesh! And thanks for the support!

/Erik
