### ISSUE TITLE
Invalid path on Windows

### ISSUE THREAD

**Issue by eriove** [FloSewn/TQMesh#7]
This project looks really interesting. I was trying to clone it but it turns out aux is a [reserved file name](https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file#naming-conventions) on Windows so I can't clone the repository (or extract it from a zip file).

Would it be possible to change the aux folder name to something else?

**Comment by FloSewn** [comment]
Hey Eriove, 

Thank you so much for your contribution - looks great! 

I will add your changes into the main branch as soon as possible.

Greetings
Flo

**Comment by FloSewn** [comment]
I just merged your changes into the main branch. 

Thanks again very much for your contribution! :-)
