### ISSUE TITLE
distorted paving mesh

### ISSUE THREAD

**Issue by OpenFoam-User** [FloSewn/TQMesh#9]
Hello,

I have tried using the example 2 to generate unstructured quad mesh but unfortunately I am not getting the same mesh (comparing the following screenshot of the mesh I get and the screenshot from the README of the project):

## Obtained mesh:

![image](https://user-images.githubusercontent.com/67183566/208435113-98a52925-47ad-44f9-b5d6-f2ed3862db05.png)

## Mesh from the README file:

![Image from README](https://github.com/FloSewn/TQMesh/raw/main/doc/Example_2.png)

Note: I have tried both the main and develop branches but I am still getting the same issue

What I am doing wrong?

**Comment by FloSewn** [comment]
Hey there,

thank you so much for pointing out this error. I just reverted back to tag v1.2.1 (e37d966) and then I get the mesh that is shown in the README file. 

It seems that the changes of commit 1cac9f9 have a negative effect on the smoothing of all-quad-meshes. 

I will fix this in the coming days! 


Greetings
Flo

**Comment by OpenFoam-User** [comment]
Many thanks for the reply.

**Comment by FloSewn** [comment]
I fixed that bug in the main branch - the mesh of example 2 should now be ok.

Greetings 
Flo

**Comment by OpenFoam-User** [comment]
Thank you for the fix. I confirm that it works as expected.
